from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
from typing import List, Optional
from datetime import datetime

app = FastAPI(title="FlashAPI", description="API de flashcards con Oracle (esquema FLASH)", version="1.0.0")
from fastapi.middleware.cors import CORSMiddleware

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # en producción se puede restringir a tu dominio
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

import oracledb
from db import get_connection


# =======================
#   MODELOS Pydantic
# =======================

class FlashcardIn(BaseModel):
    english: str
    spanish: str


class Flashcard(BaseModel):
    id: int
    english: str
    spanish: str
    created_at: Optional[datetime] = None


# =======================
#   INICIALIZACIÓN BD
# =======================

@app.on_event("startup")
def init_db():
    """
    Crea la tabla FLASH.FLASHCARDS si no existe.
    Se ejecuta automáticamente cuando arranca FastAPI.
    """
    conn = get_connection()
    cur = conn.cursor()
    try:
        cur.execute(
            """
            CREATE TABLE FLASH.FLASHCARDS (
                id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                english    VARCHAR2(200) NOT NULL,
                spanish    VARCHAR2(200) NOT NULL,
                created_at TIMESTAMP DEFAULT SYSTIMESTAMP
            )
            """
        )
        conn.commit()
        print("Tabla FLASH.FLASHCARDS creada.")
    except oracledb.Error as e:
        # ORA-00955: name is already used by an existing object
        if "ORA-00955" in str(e):
            print("Tabla FLASH.FLASHCARDS ya existe, continuando...")
        else:
            print("Error creando tabla FLASH.FLASHCARDS:", e)
            raise
    finally:
        cur.close()
        conn.close()


# =======================
#   ENDPOINTS BÁSICOS
# =======================

@app.get("/")
def home():
    return {"message": "FastAPI + Oracle (esquema FLASH) listo."}


@app.get("/test-db")
def probar():
    """
    Prueba sencilla de conexión a la base de datos.
    """
    try:
        conn = get_connection()
        cursor = conn.cursor()
        cursor.execute("SELECT 'OK' FROM DUAL")
        result = cursor.fetchone()
        cursor.close()
        conn.close()
        return {"status": result[0]}
    except Exception as e:
        # Mostramos el error para debug
        print("Error en /test-db:", e)
        raise HTTPException(status_code=500, detail=str(e))


# =======================
#   ENDPOINTS FLASHCARDS
# =======================

@app.get("/cards", response_model=List[Flashcard])
def list_cards():
    """
    Lista todas las flashcards del esquema FLASH.
    """
    conn = get_connection()
    cur = conn.cursor()
    try:
        cur.execute(
            """
            SELECT id, english, spanish, created_at
            FROM FLASH.FLASHCARDS
            ORDER BY id
            """
        )
        rows = cur.fetchall()

        cards = [
            Flashcard(
                id=row[0],
                english=row[1],
                spanish=row[2],
                created_at=row[3]
            )
            for row in rows
        ]
        return cards

    except Exception as e:
        print("Error en GET /cards:", e)
        raise HTTPException(status_code=500, detail=str(e))
    finally:
        cur.close()
        conn.close()


@app.post("/cards", response_model=Flashcard)
def create_card(card_in: FlashcardIn):
    """
    Crea una nueva flashcard en FLASH.FLASHCARDS.
    """
    conn = get_connection()
    cur = conn.cursor()
    try:
        # 1) Insertar la fila
        cur.execute(
            """
            INSERT INTO FLASH.FLASHCARDS (english, spanish)
            VALUES (:english, :spanish)
            """,
            {
                "english": card_in.english,
                "spanish": card_in.spanish,
            }
        )
        conn.commit()

        # 2) Recuperar la última fila insertada (por id más alto)
        cur.execute(
            """
            SELECT id, english, spanish, created_at
            FROM FLASH.FLASHCARDS
            WHERE id = (
                SELECT MAX(id) FROM FLASH.FLASHCARDS
            )
            """
        )
        row = cur.fetchone()
        if not row:
            raise HTTPException(
                status_code=500,
                detail="No se pudo recuperar la flashcard recién creada."
            )

        return Flashcard(
            id=row[0],
            english=row[1],
            spanish=row[2],
            created_at=row[3]
        )

    except Exception as e:
        print("Error en POST /cards:", e)
        raise HTTPException(status_code=500, detail=str(e))
    finally:
        cur.close()
        conn.close()


@app.delete("/cards/{card_id}")
def delete_card(card_id: int):
    """
    Elimina una flashcard por ID en FLASH.FLASHCARDS.
    """
    conn = get_connection()
    cur = conn.cursor()
    try:
        cur.execute(
            "DELETE FROM FLASH.FLASHCARDS WHERE id = :id",
            {"id": card_id}
        )
        deleted = cur.rowcount
        conn.commit()

        if deleted == 0:
            return {
                "deleted": False,
                "message": f"No existe una flashcard con id {card_id}"
            }

        return {
            "deleted": True,
            "message": f"Flashcard {card_id} eliminada"
        }

    except Exception as e:
        print("Error en DELETE /cards/{card_id}:", e)
        raise HTTPException(status_code=500, detail=str(e))
    finally:
        cur.close()
        conn.close()
